# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'iOS_CoreAnimation_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_CoreAnimation_Demo

   pod 'lottie-ios'
   pod 'SnapKit'



  target 'iOS_CoreAnimation_DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS_CoreAnimation_DemoUITests' do
    # Pods for testing
  end

end
